# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - before_script: python -V  # Print out python version for debugging
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install tox flake8 pytest
        pip install finam-export>=4.0.1
        pip install matplotlib
        pip install bs4
        pip install openpyxl
        pip install threading
        pip install fuzzywuzzy
        pip install pandas
        pip install numpy
        pip install pymorphy2
        pip install requests
        pip install datetime
        pip install logging
        pip install hashlib
        pip install random
        pip install math
        pip install time
        pip install xlrd
        pip install json
        pip install csv
        pip install sys
        pip install os
        pip install re
        pip install ta
    - name: Test with pytest
      run: |
        python Global_main.py test
